name: Resuable Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
        description: The branch ref to build. Leave empty to use workflow branch.
      publish:
        type: boolean
        default: false
        description: To publish the project artifacts to the Maven alternative repository.
      alt-deployment-repository:
        type: string
        default: snapshots::${{ vars.SNAPSHOTS_REPOSITORY_URL }}
        description: Maven alternative repository to which the project artifacts should be deployed.

    secrets:
      BONITA_CI_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Print variables
        run: |
          echo ref=${{ github.ref }}
          echo head_ref=${{ github.head_ref }}
          echo base_ref=${{ github.base_ref }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: bonitasoft/bonita-application-directory
          token: ${{ secrets.BONITA_CI_PAT }}
          ref: ${{ inputs.ref }}

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Maven Build
        if: ${{ !inputs.publish }}
        timeout-minutes: 60
        run: ./mvnw -ntp verify

      - name: Maven Build & Deploy
        if: ${{ inputs.publish }}
        timeout-minutes: 60
        run: ./mvnw -ntp deploy -DaltDeploymentRepository=${{ inputs.alt-deployment-repository }}
