name: Create Merge Pull Request Upstream

on:
  workflow_dispatch:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
      - "master"
      - "release-*"

jobs:
  create-merge-pr:
    uses: bonitasoft/github-workflows/.github/workflows/_reusable_create_merge_pr.yml@main
    secrets: inherit
    with:
      labels: automerge
